# Generated by Django 5.0.6 on 2024-06-27 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0011_ward_alter_hospital_district_booking_hospital_wards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='wards',
        ),
        migrations.AddField(
            model_name='ward',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='hospital.hospital'),
        ),
    ]
