# Generated by Django 5.0.6 on 2024-06-29 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0013_alter_ward_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ward',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='hospital.hospital'),
        ),
    ]
