# Generated by Django 5.0.6 on 2024-06-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0014_alter_ward_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='district',
            field=models.CharField(choices=[('Nairobi', 'Nairobi'), ('Kisumu', 'Kisumu'), ('Nakuru', 'Nakuru'), ('Eldoret', 'Eldoret'), ('Naivasha', 'Naivasha'), ('Kiambu', 'Kiambu'), ('Kikuyu', 'Kikuyu'), ('Embu', 'Embu')], max_length=100),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='hos_type',
            field=models.CharField(choices=[('Nairobi Headquarters Hospital', 'Nairobi Headquarters Hospital'), ('Medical College Hospital', 'Medical College Hospital'), ('Family Health Center', 'Family Health Center')], max_length=100),
        ),
    ]
