# Generated by Django 5.0.6 on 2024-06-29 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0015_alter_hospital_district_alter_hospital_hos_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ward',
            name='bed_numbers',
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.IntegerField()),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='hospital.ward')),
            ],
        ),
    ]
