# Generated by Django 5.0.6 on 2024-07-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0016_remove_ward_bed_numbers_bed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='bed_number',
            field=models.CharField(max_length=4),
        ),
    ]
