# Generated by Django 5.0.6 on 2024-07-02 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_bed_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bed',
            name='number',
        ),
    ]
