# Generated by Django 5.0.6 on 2024-07-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_remove_bed_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='state',
            field=models.CharField(choices=[('reserved', 'Reserved'), ('approved', 'Approved'), ('occupied', 'Occupied'), ('vacant', 'Vacant')], default='vacant', max_length=20),
        ),
    ]
