# Generated by Django 5.0.6 on 2024-07-03 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0020_alter_booking_state'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='patient.patient'),
        ),
    ]
